title: Mykyta Zharov # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master student in Mathematics @ RWTH Aachen University. Currently working as a working student @ KPMG Germany, Consulting.
  <br><br>
  Enjoy finding solutions to problems. 
  <br><br>
  <a href="https://www.linkedin.com/in/mykytazharov/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.mykytazharov.github.io/CV">View My CV</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-161203966-1 # your Google Analytics tracking ID here
