title: Mykyta Zharov # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master student @ RWTH Aachen University, studying Mathematics and a practical course in Business Administration. Specializing in Categorical Data Analysis, Machine Learning, High Dimensional Probability Theory, Statistics and Time Series Analysis. I have experience in Software Development and Statistical Data Analysis. Curious about how analyzing data can generate new insights to improve people's lives.
  <br><br>
  Currently working as a working student in KPMG Germany, Consulting.
  Enjoy finding solutions to problems.  
  <br><br>
  <a href="https://www.linkedin.com/in/mykytazharov/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-161203966-1 # your Google Analytics tracking ID here
